	--background:
	SharedMedia:Register("background", "DsmBG1", [[Interface\Addons\SharedMedia\MyMedia files\dsmbg1.tga]])
	SharedMedia:Register("background", "DsmBG2", [[Interface\Addons\SharedMedia\MyMedia files\dsmbg2.tga]])
	SharedMedia:Register("background", "DsmBG3", [[Interface\Addons\SharedMedia\MyMedia files\dsmbg3.tga]])
	--border:
	SharedMedia:Register("border", "DsmBorder1", [[Interface\Addons\SharedMedia\MyMedia files\dsmbd1.tga]])
	SharedMedia:Register("border", "DsmBorder2", [[Interface\Addons\SharedMedia\MyMedia files\dsmbd2.tga]])
	SharedMedia:Register("border", "DsmBorder3", [[Interface\Addons\SharedMedia\MyMedia files\dsmbd3.tga]])
	SharedMedia:Register("border", "DsmBorder4", [[Interface\Addons\SharedMedia\MyMedia files\dsmbd4.tga]])
	SharedMedia:Register("border", "DsmBorder5", [[Interface\Addons\SharedMedia\MyMedia files\dsmbd5.tga]])
	SharedMedia:Register("border", "DsmBorder6", [[Interface\Addons\SharedMedia\MyMedia files\dsmbd6.tga]])
	SharedMedia:Register("border", "Caith", [[Interface\Addons\SharedMedia\MyMedia files\Caith2.tga]])
    SharedMedia:Register("border", "Caith Thin", [[Interface\Addons\SharedMedia\MyMedia files\CaithThin.tga]])
    
    --font:

	SharedMedia:Register("font", "Avant Garde", [[Interface\Addons\SharedMedia\MyMedia files\avantgarde.ttf]])
    SharedMedia:Register("font", "Expressway", [[Interface\Addons\SharedMedia\MyMedia files\Expressway.TTF]])
	
	--statusbar:
    SharedMedia:Register("statusbar", "Demigod Party", [[Interface\Addons\SharedMedia\MyMedia files\Demigod Party.tga]])
	SharedMedia:Register("statusbar", "DsmB1", [[Interface\Addons\SharedMedia\MyMedia files\DsmB1.tga]])
	SharedMedia:Register("statusbar", "DsmB2", [[Interface\Addons\SharedMedia\MyMedia files\DsmB2.tga]])
	SharedMedia:Register("statusbar", "DsmB3", [[Interface\Addons\SharedMedia\MyMedia files\DsmB3.tga]])
	SharedMedia:Register("statusbar", "DsmB4", [[Interface\Addons\SharedMedia\MyMedia files\DsmB4.tga]])
	SharedMedia:Register("statusbar", "DsmB5", [[Interface\Addons\SharedMedia\MyMedia files\DsmB5.tga]])
	SharedMedia:Register("statusbar", "DsmB6", [[Interface\Addons\SharedMedia\MyMedia files\DsmB6.tga]])
	SharedMedia:Register("statusbar", "DsmB7", [[Interface\Addons\SharedMedia\MyMedia files\DsmB7.tga]])
	SharedMedia:Register("statusbar", "DsmB8", [[Interface\Addons\SharedMedia\MyMedia files\DsmB8.tga]])
	SharedMedia:Register("statusbar", "DsmB9", [[Interface\Addons\SharedMedia\MyMedia files\DsmB9.tga]])
	SharedMedia:Register("statusbar", "DsmOpaqueV1", [[Interface\Addons\SharedMedia\MyMedia files\DsmOpaqueV1.tga]])
	SharedMedia:Register("statusbar", "DsmOpaqueV2", [[Interface\Addons\SharedMedia\MyMedia files\DsmOpaqueV2.tga]])
	SharedMedia:Register("statusbar", "DsmOpaqueV3", [[Interface\Addons\SharedMedia\MyMedia files\DsmOpaqueV3.tga]])
	SharedMedia:Register("statusbar", "DsmOpaqueV4", [[Interface\Addons\SharedMedia\MyMedia files\DsmOpaqueV4.tga]])
	SharedMedia:Register("statusbar", "DsmOpaqueV5", [[Interface\Addons\SharedMedia\MyMedia files\DsmOpaqueV5.tga]])
	SharedMedia:Register("statusbar", "DsmOpaqueV6", [[Interface\Addons\SharedMedia\MyMedia files\DsmOpaqueV6.tga]])
	SharedMedia:Register("statusbar", "DsmV1", [[Interface\Addons\SharedMedia\MyMedia files\DsmV1.tga]])
	SharedMedia:Register("statusbar", "DsmV2", [[Interface\Addons\SharedMedia\MyMedia files\DsmV2.tga]])
	SharedMedia:Register("statusbar", "DsmV3", [[Interface\Addons\SharedMedia\MyMedia files\DsmV3.tga]])
	SharedMedia:Register("statusbar", "DsmV4", [[Interface\Addons\SharedMedia\MyMedia files\DsmV4.tga]])
	SharedMedia:Register("statusbar", "DsmV5", [[Interface\Addons\SharedMedia\MyMedia files\DsmV5.tga]])
	SharedMedia:Register("statusbar", "DsmV6", [[Interface\Addons\SharedMedia\MyMedia files\DsmV6.tga]])
	SharedMedia:Register("statusbar", "DsmV7", [[Interface\Addons\SharedMedia\MyMedia files\DsmV7.tga]])
	SharedMedia:Register("statusbar", "DsmV8", [[Interface\Addons\SharedMedia\MyMedia files\DsmV8.tga]])
	SharedMedia:Register("statusbar", "DsmV9", [[Interface\Addons\SharedMedia\MyMedia files\DsmV9.tga]])
    SharedMedia:Register("statusbar", "Curved Castbar", [[Interface\Addons\SharedMedia\MyMedia files\CurvedCastBar.tga]])
    SharedMedia:Register("statusbar", "Demigod 2", [[Interface\Addons\SharedMedia\MyMedia files\Demigod2.tga]])
    SharedMedia:Register("statusbar", "ALongcast", [[Interface\Addons\SharedMedia\MyMedia files\Longcast.tga]])
    SharedMedia:Register("statusbar", "Healbot Round", [[Interface\Addons\SharedMedia\MyMedia files\HealbotRound.tga]])
    SharedMedia:Register("statusbar", "PixelJunk", [[Interface\Addons\SharedMedia\MyMedia files\pixeljunk.tga]])