local L = LibStub("AceLocale-3.0"):NewLocale("YurysRuneDisplay", "deDE")
if not L then return end
L["About"] = "Über"
L["Arc"] = "Arc"
L["Author"] = "Author"
L["Blizzard frame"] = "Blizzard-Rahmen"
L["Block"] = "Klops"
L["Color of the numerical cooldown"] = "Farbe - CooldownTimer"
L["Config"] = "Config"
L["Cooldown color"] = "Farbe - Cooldown"
L["Default"] = "Standard"
L["Enable/disable the numerical cooldown"] = "Cooldown-Timer aktivieren"
L["Happy mouth"] = "Happy"
L["Lock"] = "Sperre"
L["Locks Yury's RuneDisplay, preventing moving it"] = "Sperrt YRD"
L["Notes"] = "Notizen"
L["Numerical Cooldown"] = "Cooldown-Timer"
L["Out Of Combat Alpha-value"] = "Alpha - OOC"
L["Reset"] = "Reset"
L["Resets all options to default values"] = "Setzt alle Optionen auf Standardwerte"
L["Rune"] = "Rune"
L["Sad mouth"] = "Sad"
L["Scale"] = "Skala"
L["Scale Yury's RuneDisplay; make it bigger (>1) or smaller (<1)"] = "Skaliert YRD"
L["Sets the OOCA of Yury's RuneDisplay, to make it less visible when not in combat"] = "Alpha - OOC"
L["Sets the arc-type of Yury's RuneDisplay"] = "Layout"
L["Shows the configuration screen"] = "Zeigt Config"
L["Shows/hides Blizzard's default runebar"] = "Blizzard-Rahmen zeigen"
L["Straight line"] = "Straight"
L["Unlock"] = "Entsperren"
L["Unlocks Yury's RuneDisplay, allowing it to be moved"] = "Entsperrt YRD"
L["Version"] = "Version"
L["Very simple and lightweight addon for display of a Death Knight's runes (because the default frame is uncontrollable)"] = "Simple Runenanzeige - IsyGoing, quasi!"
L["Yury's RuneDisplay"] = "Yury's Rune Display"
L["Yury's RuneDisplay enabled. For options: /"] = [=[YRD *** Yury'sRuneDisplay aktiv
Optionen --->   /]=]
L["yrd"] = "yrd"

