local L = LibStub("AceLocale-3.0"):NewLocale("YurysRuneDisplay", "enUS", true)
L["About"] = true
L["Arc"] = true
L["Author"] = true
L["Blizzard frame"] = true
L["Block"] = true
L["Color of the numerical cooldown"] = true
L["Config"] = true
L["Cooldown color"] = true
L["Default"] = true
L["Enable/disable the numerical cooldown"] = true
L["Happy mouth"] = true
L["Lock"] = true
L["Locks Yury's RuneDisplay, preventing moving it"] = true
L["Notes"] = true
L["Numerical Cooldown"] = true
L["Out Of Combat Alpha-value"] = true
L["Reset"] = true
L["Resets all options to default values"] = true
L["Rune"] = true
L["Sad mouth"] = true
L["Scale"] = true
L["Scale Yury's RuneDisplay; make it bigger (>1) or smaller (<1)"] = true
L["Sets the OOCA of Yury's RuneDisplay, to make it less visible when not in combat"] = true
L["Sets the arc-type of Yury's RuneDisplay"] = true
L["Shows the configuration screen"] = true
L["Shows/hides Blizzard's default runebar"] = true
L["Straight line"] = true
L["Unlock"] = true
L["Unlocks Yury's RuneDisplay, allowing it to be moved"] = true
L["Version"] = true
L["Very simple and lightweight addon for display of a Death Knight's runes (because the default frame is uncontrollable)"] = true
L["Yury's RuneDisplay"] = true
L["Yury's RuneDisplay enabled. For options: /"] = true
L["yrd"] = true

