local L = LibStub("AceLocale-3.0"):NewLocale("YurysRuneDisplay", "ruRU")
if not L then return end
L["About"] = "Об"
L["Arc"] = "Arc" -- Requires localization
L["Author"] = "Автор"
L["Blizzard frame"] = "Blizzard frame" -- Requires localization
L["Block"] = "Block" -- Requires localization
L["Color of the numerical cooldown"] = "Color of the numerical cooldown" -- Requires localization
L["Config"] = "Настройки"
L["Cooldown color"] = "Cooldown color" -- Requires localization
L["Default"] = "По умолчанию"
L["Enable/disable the numerical cooldown"] = "Enable/disable the numerical cooldown" -- Requires localization
L["Happy mouth"] = "Happy mouth" -- Requires localization
L["Lock"] = "Блокировать"
L["Locks Yury's RuneDisplay, preventing moving it"] = "Блокировать Yury's RuneDisplay, перемещение невозможно."
L["Notes"] = "Заметки"
L["Numerical Cooldown"] = "Numerical Cooldown" -- Requires localization
L["Out Of Combat Alpha-value"] = "Прозрачность вне боя"
L["Reset"] = "Сброс"
L["Resets all options to default values"] = "Сброс всех настроек на значения по умолчанию"
L["Rune"] = "Руны"
L["Sad mouth"] = "Sad mouth" -- Requires localization
L["Scale"] = "Масштаб"
L["Scale Yury's RuneDisplay; make it bigger (>1) or smaller (<1)"] = "Масштаб Yury's RuneDisplay; больше (>1) или меньше (<1)"
L["Sets the OOCA of Yury's RuneDisplay, to make it less visible when not in combat"] = "Sets the OOCA of Yury's RuneDisplay, to make it less visible when not in combat" -- Requires localization
L["Sets the arc-type of Yury's RuneDisplay"] = "Sets the arc-type of Yury's RuneDisplay" -- Requires localization
L["Shows the configuration screen"] = "Открывает окно настроек"
L["Shows/hides Blizzard's default runebar"] = "Показать/скрыть стандартную панель рун"
L["Straight line"] = "Straight line" -- Requires localization
L["Unlock"] = "Разблокировать"
L["Unlocks Yury's RuneDisplay, allowing it to be moved"] = "Освобождает Yury's RuneDisplay, позваляет перемещать."
L["Version"] = "Версия"
L["Very simple and lightweight addon for display of a Death Knight's runes (because the default frame is uncontrollable)"] = "Very simple and lightweight addon for display of a Death Knight's runes (because the default frame is uncontrollable)" -- Requires localization
L["Yury's RuneDisplay"] = "Yury's RuneDisplay"
L["Yury's RuneDisplay enabled. For options: /"] = "Yury's RuneDisplay включён. Настройки: /"
L["yrd"] = "yrd" -- Requires localization
