local L = LibStub("AceLocale-3.0"):NewLocale("YurysRuneDisplay", "zhTW")
if not L then return end
L["About"] = "About" -- Requires localization
L["Arc"] = "Arc" -- Requires localization
L["Author"] = "Author" -- Requires localization
L["Blizzard frame"] = "Blizzard frame" -- Requires localization
L["Block"] = "Block" -- Requires localization
L["Color of the numerical cooldown"] = "Color of the numerical cooldown" -- Requires localization
L["Config"] = "Config" -- Requires localization
L["Cooldown color"] = "Cooldown color" -- Requires localization
L["Default"] = "Default" -- Requires localization
L["Enable/disable the numerical cooldown"] = "Enable/disable the numerical cooldown" -- Requires localization
L["Happy mouth"] = "Happy mouth" -- Requires localization
L["Lock"] = "Lock" -- Requires localization
L["Locks Yury's RuneDisplay, preventing moving it"] = "Locks Yury's RuneDisplay, preventing moving it" -- Requires localization
L["Notes"] = "Notes" -- Requires localization
L["Numerical Cooldown"] = "Numerical Cooldown" -- Requires localization
L["Out Of Combat Alpha-value"] = "Out Of Combat Alpha-value" -- Requires localization
L["Reset"] = "Reset" -- Requires localization
L["Resets all options to default values"] = "Resets all options to default values" -- Requires localization
L["Rune"] = "Rune" -- Requires localization
L["Sad mouth"] = "Sad mouth" -- Requires localization
L["Scale"] = "Scale" -- Requires localization
L["Scale Yury's RuneDisplay; make it bigger (>1) or smaller (<1)"] = "Scale Yury's RuneDisplay; make it bigger (>1) or smaller (<1)" -- Requires localization
L["Sets the OOCA of Yury's RuneDisplay, to make it less visible when not in combat"] = "Sets the OOCA of Yury's RuneDisplay, to make it less visible when not in combat" -- Requires localization
L["Sets the arc-type of Yury's RuneDisplay"] = "Sets the arc-type of Yury's RuneDisplay" -- Requires localization
L["Shows the configuration screen"] = "Shows the configuration screen" -- Requires localization
L["Shows/hides Blizzard's default runebar"] = "Shows/hides Blizzard's default runebar" -- Requires localization
L["Straight line"] = "Straight line" -- Requires localization
L["Unlock"] = "Unlock" -- Requires localization
L["Unlocks Yury's RuneDisplay, allowing it to be moved"] = "Unlocks Yury's RuneDisplay, allowing it to be moved" -- Requires localization
L["Version"] = "Version" -- Requires localization
L["Very simple and lightweight addon for display of a Death Knight's runes (because the default frame is uncontrollable)"] = "Very simple and lightweight addon for display of a Death Knight's runes (because the default frame is uncontrollable)" -- Requires localization
L["Yury's RuneDisplay"] = "Yury's RuneDisplay" -- Requires localization
L["Yury's RuneDisplay enabled. For options: /"] = "Yury's RuneDisplay enabled. For options: /" -- Requires localization
L["yrd"] = "yrd" -- Requires localization
